---
title: "Neural Network"
author: "Muneeb Aslam"
date: "02/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning=FALSE}
set.seed(10)
library(neuralnet)
library(fastDummies)
```


```{r}
#loading the dataset
bankData <- read.delim("bank-full.csv", sep =";" ,header = T, strip.white = TRUE)

#clean-up code to change unknowns to 'NA'
bankData[bankData == "unknown"] <- NA

#checking how many NA's the columns 'contact' and 'poutcome' account for
((sum(is.na(bankData$contact)) + sum(is.na(bankData$poutcome)))/ sum(is.na(bankData)))*100

#Removing the two columns whcih account for 95.9% of the NA's
bankData = bankData[,-which(colnames(bankData) == "poutcome")]
bankData = bankData[,-which(colnames(bankData) == "contact")]
str(bankData)
```


```{r}
#Creating dummy variables for all data entries that were categrorical (factors)
#This is necessary to use a neural network as we need to work with quantitative variables
bankdataNN = fastDummies::dummy_cols(bankData,select_columns = c("y","job","marital","education","default","housing","loan","month"), remove_first_dummy = TRUE)
head(bankdataNN)

#Removing these variables once dummy ones have been created
drop = c("y","job","marital","education","default","housing","loan","month")
bankdataNN = bankdataNN[,!(colnames(bankdataNN) %in% drop)]

#Removing NAs as neuralnet model would not run with them included
bankdataNN = na.omit(bankdataNN)

#Changing some column names as they had special characters in them
colnames(bankdataNN)
colnames(bankdataNN)[9] = "job_blue_collar"
colnames(bankdataNN)[14] = "job_self_employed"
```


```{r}
#80/20 train/test data split
test_indices = sample(1:nrow(bankdataNN), size = 0.2*nrow(bankdataNN), replace = FALSE)
training_set = bankdataNN[-test_indices,]
test_set = bankdataNN[test_indices,]

#Creating ANN model
model = neuralnet(y_yes ~., hidden = 3, stepmax = 1e6, data = training_set, linear.output = FALSE)
plot(model)
```


```{r}
#Evaluating model
predictions = predict(model,test_set)
confusion_matrix = table(test_set$y_yes, apply(predictions, 1, which.max))
confusion_matrix

nrow(test_set) == sum(confusion_matrix)
classification_Rate = sum(diag(confusion_matrix))/sum(confusion_matrix)*100
classification_Rate
```
